# Generated by Django 4.1 on 2022-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('reminder', models.DateTimeField()),
            ],
        ),
    ]
